id: PE2B071CC
initial_creation_type: input
source_metadata:
  title: Nepal Series
  language: zh
  description: 'Texts related to the kingdom of Nepal, known to Tibetans as the ''land
    of wool'' (bal yul):'
  volume:
    8204417f3d644f53a80938e8b153d9f5:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Guides
    8716117afad042359ba2866bc5e7296a:
      title: A Short Guide to Yangleshö in Nepal
      parent: Guides
    3be19c3c2c064352868edc3616268bc7:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: History
    f72a41cfa7d2468a81a495e640d2d7d5:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Offering
    5f416c88082f434096a2dc2edc026329:
      title: In Praise of Yangleshö in Nepal
      parent: Praise
    44982fcc9f8d478dab2834051d4e1b8e:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Praise
    42af91eebc4d4764a3d7a6942aa82bc3:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Praise
    d019b9155aba4f948bea5871aaf10e77:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    3e3a3c635f9b496c802329ce8eeab541:
      title: A Prayer to the Stūpa of Jarung Khashor in Boudha
      parent: Prayers
    2f31b55a0a30446cb12214d13663faf5:
      title: A Prayer to the Svayambhū Stūpa in Nepal
      parent: Prayers
    28086176a9844c38ba16c09287347520:
      title: A Prayer to the Three Stūpas of Nepal
      parent: Prayers
    af507ecaadda44619927b9ac8db08ce6:
      title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice
        to the Tigress
      parent: Prayers
    0e4459595cd947cdaffff93278262cda:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Songs
    d16669f9256146cb93504eafa2f2e335:
      title: Upon Arriving at Yangleshö
      parent: Songs
created_at: '2022-03-01T04:47:23.840799'
last_modified_at: '2022-03-01T04:47:23.840802'
